---     
 - name: Get hostname
   nclu: 
     commands:
       - show hostname
   register: host 

 - name: Set hostname fact
   vars:
      hostname: "{{ host.msg }}"
   set_fact:
      hostname: "{{ hostname }}"
      
 - name: Get CLAG
   nclu:
     commands:
      - show clag json
   register: clag
     
 - name: Set clag fact
   vars:
      clag_data: "{{ clag.msg }}"
      clag_status: "{{ clag_data.status }}"
      clag_backupActive: "{{ clag_status.backupActive }}"
      clag_backupIp: "{{ clag_status.backupIp }}"
      clag_ourPriority: "{{ clag_status.ourPriority }}"
      clag_ourRole: "{{ clag_status.ourRole }}"
      clag_peerAlive: "{{ clag_status.peerAlive }}"
      clag_peerIf: "{{ clag_status.peerIf }}"
      clag_peerIp: "{{ clag_status.peerIp }}"
      clag_peerPriority: "{{ clag_status.peerPriority }}"
      clag_peerRole: "{{ clag_status.peerRole }}"
   set_fact:
      clag_status: "{{ clag_status }}"  
      clag_backupActive: "{{ clag_backupActive }}"
      clag_backupIp: "{{ clag_status.backupIp }}"
      clag_ourPriority: "{{ clag_status.ourPriority }}"
      clag_ourRole: "{{ clag_status.ourRole }}"
      clag_peerAlive: "{{ clag_status.peerAlive }}"
      clag_peerIf: "{{ clag_status.peerIf }}"
      clag_peerIp: "{{ clag_status.peerIp }}"
      clag_peerPriority: "{{ clag_status.peerPriority }}"
      clag_peerRole: "{{ clag_status.peerRole }}"
      
 - name: Get Code Version
   nclu:
     commands:
       - show ver json
   register: code

 - name: Set Code Facts
   vars:
     code_data: "{{ code.msg }}"
     code_ver: "{{ code_data.os }}"
   set_fact:
     code_ver: "{{ code_ver }}"

 - name: Get Interface Data
   nclu: 
     commands:
       - show interface json
   register: interfaces
   
 - name: Register Interface Facts
   vars:
     interface_data: "{{ interfaces.msg }}"
   set_fact:
     interface_data: "{{ interface_data }}"

 - name: Get OSPF routes
   nclu:
     commands:
        - show ospf neighbor json
   register: ospf_status
   
 - name: Register OSPF Facts
   vars:
     ospf_info: "{{ ospf_status.msg }}"
     ospf_data: "{{ ospf_info.neighbors }}"
   set_fact:
     ospf_data: "{{ ospf_data }}"      
    
 - name: Get BGP routes
   nclu:
     commands:
        - show bgp summary json
   register: bgp_status 

 - name: Register BGP Facts
   vars:
     bgp_info: "{{ bgp_status.msg }}"
     bgp_ipv4: "{{ bgp_info['ipv4 unicast'] }}"
     bgp_data: "{{ bgp_ipv4.peers }}"
     bgp_peercount: "{{ bgp_ipv4.peerCount }}"
   set_fact:
     bgp_data: "{{ bgp_data }}" 
     bgp_peercount: "{{ bgp_peercount }}"

 - name: Get service state
   service_facts:
   register: service_status
   
 - name: Register Service Facts
   set_fact:
     service_status: "{{ service_status }}"   

 - name: Ping core01
   vars: 
     super_net: "{{ snet }}"
   become: true 
   shell: ping {{ super_net }}1.3 -c 5 -i .2 | grep loss
   register: ping_core01_status

 - name: Ping core02
   vars: 
     super_net: "{{ snet }}"
   become: true 
   shell: ping {{ super_net }}1.4 -c 5 -i .2 | grep loss
   register: ping_core02_status

 - name: Ping fw01
   vars: 
     super_net: "{{ snet }}"
   become: true 
   shell: ping {{ super_net }}1.100 -c 5 -i .2 | grep loss
   register: ping_fw01_status

 - name: Ping fw02
   vars: 
     super_net: "{{ snet }}"
   become: true 
   shell: ping {{ super_net }}1.101 -c 5 -i .2 | grep loss
   register: ping_fw02_status   
   
 - name: Ping vpn01
   vars: 
     super_net: "{{ snet }}"
   become: true 
   shell: ping {{ super_net }}150.24 -c 5 -i .2 | grep loss
   register: ping_vpn01_status   

 - name: Ping vpn02
   vars: 
     super_net: "{{ snet }}"
   become: true 
   shell: ping {{ super_net }}150.23 -c 5 -i .2 | grep loss
   register: ping_vpn02_status   

 - name: Ping google_dns
   vars: 
     super_net: "{{ snet }}"
   become: true 
   shell: ping 8.8.8.8 -c 5 -i .2 | grep loss
   register: ping_google_status     
   
 - name: Register Ping Data
   vars:
     ping_core01: "{{ ping_core01_status.stdout }}"
     ping_core02: "{{ ping_core02_status.stdout }}"
     ping_fw01: "{{ ping_fw01_status.stdout }}"
     ping_fw02: "{{ ping_fw02_status.stdout }}"
     ping_vpn01: "{{ ping_vpn01_status.stdout }}"
     ping_vpn02: "{{ ping_vpn02_status.stdout }}"
     ping_google: "{{ ping_google_status.stdout }}"    
   set_fact:
     ping_core01_status: "{{ ping_core01 }}"
     ping_core02_status: "{{ ping_core02 }}"
     ping_fw01_status: "{{ ping_fw01 }}"
     ping_fw02_status: "{{ ping_fw02 }}"
     ping_vpn01_status: "{{ ping_vpn01 }}"
     ping_vpn02_status: "{{ ping_vpn02 }}"
     ping_google_status: "{{ ping_google }}" 
   















 