# this file should contain expected values for each parameter
core01_clag_expected:
  clag_backupActive: True
  clag_backupIp: "{{ hostvars['core01']['snet'] }}1.3"
  clag_ourPriority: '4096' 
  clag_ourRole: 'primary'
  clag_peerAlive: True
  clag_peerIf: 'peerlink.4094'
  clag_peerIp: '192.168.1.2'
  clag_peerPriority: '8192'
  clag_peerRole: 'secondary'
core02_clag_expected:
  clag_backupActive: True
  clag_backupIp: "{{ hostvars['core02']['snet'] }}1.2"
  clag_ourPriority: '8192' 
  clag_ourRole: 'secondary'
  clag_peerAlive: True
  clag_peerIf: 'peerlink.4094'
  clag_peerIp: '192.168.1.1'
  clag_peerPriority: '4096'
  clag_peerRole: 'primary'
core01_ospf_neigh_count_expected: 3
core01_ospf_neigh_status_expected: 'Full\/DR'
core01_bgp_neigh_count_expected: '3'
core01_bgp_neigh_status_expected: 'Established'
core02_ospf_neigh_count_expected: 1
core02_ospf_neigh_status_expected: 'Full\/Backup'
core02_bgp_neigh_count_expected: '3'
core02_bgp_neigh_status_expected: 'Established'
cumulus_services_expected:
  dhcrelay.service: 'running'
  frr.service: 'running'
  ntp.service: 'running'
  snmpd.service: 'running'  
dmvpn01_interface_expected:
# place expected interface values for dmvpn01 here
  GigabitEthernet2/1/0: 'up'
  GigabitEthernet2/1/1: 'administratively down'
  GigabitEthernet2/1/2: 'up'
  GigabitEthernet2/1/3: 'up'
  Tunnel0: 'up'
  Loopback77: 'up'
  Loopback78: 'up'
dmvpn02_interface_expected:
  GigabitEthernet2/1/0: 'administratively down'
  GigabitEthernet2/1/1: 'up'
  GigabitEthernet2/1/2: 'up'
  GigabitEthernet2/1/3: 'up'
  Tunnel1: 'up'
  Loopback77: 'up'
  Loopback78: 'up'
dmvpn01_lldp_expected:
  GigabitEthernet2/1/0: 'core01$uplink:vpn01 gi2/1/0'
  GigabitEthernet2/1/2: 'core01$uplink:vpn01 gi2/1/2 via fw01'   
dmvpn02_lldp_expected:
  GigabitEthernet2/1/1: 'core02$uplink:vpn02 gi2/1/1'
  GigabitEthernet2/1/2: 'core01$uplink:vpn02 gi2/1/2 via fw01'
dmvpn_code_ver: '15.15.15'
cumulus_code_ver: '3.7.9'
core01_ping_expected:
  ping_core01_status: '5 packets transmitted, 5 received'
  ping_core02_status: '5 packets transmitted, 5 received'
  ping_fw01_status: '5 packets transmitted, 5 received'
  ping_fw02_status: '5 packets transmitted, 5 received'
  ping_vpn01_status: '5 packets transmitted, 5 received'
  ping_vpn02_status: '5 packets transmitted, 5 received'
  ping_google_status: '5 packets transmitted, 5 received'
core02_ping_expected:
  ping_core01_status: '5 packets transmitted, 5 received'
  ping_core02_status: '5 packets transmitted, 5 received'
  ping_fw01_status: '5 packets transmitted, 5 received'
  ping_fw02_status: '5 packets transmitted, 5 received'
  ping_vpn01_status: '5 packets transmitted, 5 received'
  ping_vpn02_status: '5 packets transmitted, 5 received'
  ping_google_status: '5 packets transmitted, 5 received' 
core_physical_interfaces:
 1:
    name: swp1 
    description: 'handoff'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP'    
 2: 
    name: swp2
    description: 'VPN01'
    core01_expected_status: 'UP'
    core02_expected_status: 'DN'    
 3: 
    name: swp3    
    description: 'Firewall-5/4'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP'      
 4: 
    name: swp4    
    description: 'VPN02'
    core01_expected_status: 'DN'    
    core02_expected_status: 'UP'    
 5:
    name: swp5    
    description: 'Firewall-5/6'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP'  
 6:
    name: swp6    
    description: 'Firewall-5/1'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP'      
 7:
    name: swp7
    description: 'Firewall-5/2'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP'      
 8:
    name: swp8    
    description: 'Firewall-5/3'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP'      
 31:
    name: swp31
    description: 'Awesome-Port'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP'      
 47:
    name: swp47
    description: 'Peerlink'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP'      
 48:
    name: swp48
    description: 'Peerlink'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP'      
 peerlink:
    name: peerlink
    description: 'Peerlink' 
    core01_expected_status: 'UP'
    core02_expected_status: 'UP'      
core_vlan_interfaces:
 2:
    name: vlan2
    description: 'vlan-name-1'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP'      
 3:
    name: vlan3
    description: 'vlan-name-2'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP'  
 4:
    name: vlan4
    description: 'vlan-name-3'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 17:
    name: vlan17
    description: 'vlan-name-6'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 18:
    name: vlan18
    description: 'vlan-name-7'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 19:
    name: vlan19
    description: 'vlan-name-8'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 20:
    name: vlan20
    description: 'vlan-name-9'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 21:
    name: vlan21
    description: 'vlan-name-10'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 22:    
    name: vlan22
    description: 'vlan-name-11'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 23:
    name: vlan23
    description: 'vlan-name-12'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 24:
    name: vlan24
    description: 'vlan-name-11-wlan'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 25:
    name: vlan25
    description: 'vlan-name-14'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 26:
    name: vlan26
    description: 'vlan-name-15'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 27:
    name: vlan27
    description: 'vlan-name-16'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 28:
    name: vlan28
    description: 'vlan-name-17'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 29:
    name: vlan29
    description: 'vlan-name-18'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 30: 
    name: vlan30
    description: 'vlan-name-19'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 31:
    name: vlan31
    description: 'vlan-name-20'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 32:
    name: vlan32
    description: 'vlan-name-21'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 33:    
    name: vlan33
    description: 'vlan-name-20-wlan'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 34:
    name: vlan34
    description: 'vlan-name-23'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 35:
    name: vlan35
    description: 'vlan-name-24'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 36:
    name: vlan36
    description: 'vlan-name-25'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 37:
    name: vlan37
    description: 'vlan-name-24-wlan'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 38:
    name: vlan38
    description: 'vlan-name-27'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 39:    
    name: vlan39
    description: 'vlan-name-28'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 40: 
    name: vlan40
    description: 'vlan-name-24-ops'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 41:     
    name: vlan41
    description: 'cs-vlan-name-24-ops'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 42:    
    name: vlan42
    description: 'vlan-name-31'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 43: 
    name:  vlan43
    description: 'vlan-name-32'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 44:
    name: vlan44
    description: 'vlan-name-33'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 45: 
    name: vlan45
    description: 'vlan-name-34'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 46: 
    name: vlan46
    description: 'vlan-name-35'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 47: 
    name: vlan47
    description: 'vlan-name-36'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 48: 
    name: vlan48
    description: 'vlan-name-37'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 49: 
    name: vlan49
    description: 'vlan-name-38'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 50: 
    name: vlan50
    description: 'vlan-name-39'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 51: 
    name: vlan51
    description: 'vlan-name-40'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 52: 
    name: vlan52
    description: 'vlan-name-41'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 53: 
    name: vlan53
    description: 'vlan-name-42'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP' 
 54: 
    name: vlan54
    description: 'vlan-name-43'
    core01_expected_status: 'UP'
    core02_expected_status: 'UP'
aruba_access_radius_server_expected: "{{ hostvars['report-server']['snet'] }}111.77"
aruba_access_code_ver_expected: 'WC.7.01.0001'
fw01_code_ver_expected: '7.7.7'
fw01_ha_enabled_expected: True
fw01_ha_state_expected: 'active'
fw01_ip_expected: "{{ hostvars['report-server']['snet'] }}1.100"
fw01_hostname_expected: "{{ hostvars['report-server']['site'] }}-fw01"
fw02_code_ver_expected: '7.7.7'
fw02_ha_enabled_expected: True
fw02_ha_state_expected: 'passive'
fw02_hostname_expected: "{{ hostvars['report-server']['site'] }}-fw02"
fw02_ip_expected: "{{ hostvars['report-server']['snet'] }}1.101"

   